services:
  nature_ros2:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: nature_ros2
    entrypoint: /ros_entrypoint.sh
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # si se usa GUI en Linux (MacOS requiere XQuartz)
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    tty: true
    stdin_open: true
    network_mode: "host"